version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore-cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Check for JS incompatibility
          command: yarn test:es-check:es5 && yarn test:es-check:es2015:module
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Run Tests
          command: yarn run ci:test
          environment:
            MOCHA_FILE: test-results.xml
          when: always
      - run:
          name: Generate Coverage
          command: yarn run ci:coverage
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: test-results.xml
      - store_test_results:
          path: test-results.xml
